---
permalink: rhel-install/task-upgrade-mysql-on-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, upgrade, mysql, linux 
summary: Puede realizar la actualización a una versión más reciente de MySQL en el servidor Linux en el que está instalado OnCommand Workflow Automation para obtener soluciones para vulnerabilidades de seguridad. 
---
= Actualice MySQL en Linux
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar la actualización a una versión más reciente de MySQL en el servidor Linux en el que está instalado OnCommand Workflow Automation para obtener soluciones para vulnerabilidades de seguridad.

.Lo que necesitará
Debe tener privilegios raíz para el sistema Linux en el que está instalado WFA.


NOTE: Antes de reinstalar WFA 4.2, debe eliminar el directorio de datos MySQL si ha desinstalado MySQL.

.Acerca de esta tarea
Sólo puede actualizar a actualizaciones secundarias de MySQL 5.7, por ejemplo, 5.7.1 a 5.7.2 . Por ejemplo, la versión 5.8 de no puede actualizarse a las versiones principales de MySQL.

.Pasos
. Inicie sesión como usuario raíz en el equipo host de WFA.
. Descargue la versión más reciente de MySQL Community Server `.rpm` paquete en el sistema de destino.
. Destar el paquete a un directorio del sistema de destino.
. Obtendrá varias `.rpm` Paquetes en el directorio después de anular el paquete, pero WFA sólo necesita los siguientes paquetes rpm:
+
** mysql-community-client-5.7.x.
** mysql-community-libs-5.7.x.
** mysql-community-server-5.7.x.
** mysql-community-common-5.7.x.
** mysql-community-libs-compat-5.7.x
+
Eliminar el resto `.rpm` paquetes. La instalación de todos los paquetes en un paquete de RPM no causará ningún problema.



. En el símbolo del sistema, detenga la base de datos y los servicios del servidor de WFA:
+
`service wfa-db stop`

+
`service wfa-server stop`

. Invoque la actualización de MySQL mediante el siguiente comando:
+
`rpm -uvh *.rpm`

+
*.rpm se refiere a `.rpm` Paquetes en el directorio en el que descargó la versión más reciente de MySQL.

. Inicie los servicios de WFA:
+
`service wfa-db start`

+
`service wfa-server start`


