---
permalink: rhel-install/task-configure-snmp.html 
sidebar: sidebar 
keywords: configure, snmp 
summary: 'Puede configurar OnCommand Workflow Automation (WFA) para que envíe capturas de protocolo simple de gestión de redes (SNMP) acerca del estado de las operaciones del flujo de trabajo.' 
---
= Configure SNMP
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede configurar OnCommand Workflow Automation (WFA) para que envíe capturas de protocolo simple de gestión de redes (SNMP) acerca del estado de las operaciones del flujo de trabajo.

.Acerca de esta tarea
La WFA `.mib` El archivo proporciona información acerca de las capturas que envía el servidor de WFA. La `.mib` el archivo se encuentra en la `<WFA_install_location>\wfa\bin\wfa.mib` directorio en el servidor de WFA.


NOTE: El servidor WFA envía todas las notificaciones de captura con un identificador de objeto genérico (1.3.6.1.4.1.789.1.1.12.0).

No se pueden usar cadenas de comunidad SNMP como _Community_String@SNMP_host_ para la configuración de SNMP.

.Pasos
. Inicie sesión en WFA a través de un navegador web como usuario administrador y acceda al servidor de WFA.
. Haga clic en *Configuración* y en *Configuración* haga clic en *SNMP*.
. Active la casilla de verificación *Activar SNMP*.
. Introduzca una dirección IPv4 o IPv6 o el nombre de host y el número de puerto del host de gestión.
+
WFA envía capturas SNMP al número de puerto especificado. El número de puerto predeterminado es 162.

. En la sección *notificar*, seleccione una o varias de las siguientes casillas de verificación:
+
** Se inició la ejecución del flujo de trabajo
** La ejecución del flujo de trabajo se ha realizado correctamente
** La ejecución del flujo de trabajo ha fallado o se ha realizado correctamente
** Ejecución del flujo de trabajo en espera de aprobación
** Error de adquisición


. Haga clic en *Enviar notificación de prueba* para comprobar la configuración.
. Haga clic en *Guardar*.

