---
permalink: rhel-install/task-restore-regular-the-oncommand-workflow-automation-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: oncommand workflow automation, wfa, cli, restore 
summary: 'Puede realizar una restauración normal de la base de datos de OnCommand Workflow Automation (WFA) de la que hizo backup anteriormente mediante la interfaz de línea de comandos (CLI). En una restauración normal, solo puede restaurar la base de datos de WFA.' 
---
= Restaure (regularmente) la base de datos de WFA con la CLI
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede realizar una restauración normal de la base de datos de OnCommand Workflow Automation (WFA) de la que hizo backup anteriormente mediante la interfaz de línea de comandos (CLI). En una restauración normal, solo puede restaurar la base de datos de WFA.

.Lo que necesitará
* Debe haber creado un backup de la base de datos WFA.
* Debe tener credenciales de administrador o de arquitecto.


.Pasos
. En el símbolo del sistema del shell, desplácese hasta el siguiente directorio en el servidor de WFA:
+
`WFA_install_location/wfa/bin`

+
`wfa_install_location` Es el directorio de instalación de WFA.

. Restaure la base de datos de WFA:
+
`wfa --restore --user=user_name [--password=password] [--location=path]`

+
** _user_name_ es el nombre de usuario del usuario admin o del arquitecto.
** _password_ es la contraseña del usuario.
+
Si no ha proporcionado la contraseña, debe introducir la contraseña cuando se le solicite.

** _path_ es la ruta completa del directorio al archivo de restauración.


. Compruebe que la operación de restauración se ha realizado correctamente y que se puede acceder a WFA.

