---
settings:
  name: OnCommand Workflow Automation 5.0
  downlevel: true
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de OnCommand Workflow Automation 5.0
    url: "/index.html"
  - title: Notas de la versión
    url: "/reference-releasenotes.html"
  - section: rhel-install
  - section: windows-install
  - section: help
  - section: workflows
  - title: Avisos legales
    url: "/legal-notices.html"
