---
permalink: windows-install/concept-wfa-data-sources.html 
sidebar: sidebar 
keywords: oncommand workflow automation, data. sources 
summary: 'OnCommand Workflow Automation (WFA) funciona con datos que se adquieren de orígenes de datos. Varias versiones de Data Center Manager de Active IQ y VMware vCenter Server se proporcionan como tipos de origen de datos de WFA predefinidos. Debe tener en cuenta los tipos de origen de datos predefinidos antes de configurar los orígenes de datos para la adquisición de datos.' 
---
= Orígenes de datos de OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) funciona con datos que se adquieren de orígenes de datos. Varias versiones de Data Center Manager de Active IQ y VMware vCenter Server se proporcionan como tipos de origen de datos de WFA predefinidos. Debe tener en cuenta los tipos de origen de datos predefinidos antes de configurar los orígenes de datos para la adquisición de datos.

Un origen de datos es una estructura de datos de sólo lectura que sirve como conexión al objeto de origen de datos de un tipo de origen de datos específico. Por ejemplo, un origen de datos puede ser una conexión a una base de datos del Administrador de centros de datos Active IQ de un tipo de origen de datos de Active IQ Data Center Manager 6.3. Puede añadir un origen de datos personalizado a WFA tras definir el tipo de origen de datos necesario.

Para obtener más información sobre los tipos de origen de datos predefinidos, consulte matriz de interoperabilidad.

*Información relacionada*

http://mysupport.netapp.com/matrix["Herramienta de matriz de interoperabilidad de NetApp"^]
