---
permalink: windows-install/task-install-workflow-automation-on-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, install, windows 
summary: 'Puede instalar OnCommand Workflow Automation (WFA) para crear y personalizar flujos de trabajo de almacenamiento para automatizar las tareas de almacenamiento que se realicen en su entorno.' 
---
= Instale OnCommand Workflow Automation en Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede instalar OnCommand Workflow Automation (WFA) para crear y personalizar flujos de trabajo de almacenamiento para automatizar las tareas de almacenamiento que se realicen en su entorno.

.Lo que necesitará
* Debe haber revisado los requisitos previos de instalación.
+
xref:reference-prerequisites-for-installing-workflow-automation.adoc[Requisitos previos para instalar Workflow Automation]

* Si está instalando WFA en un sistema donde WFA se había instalado previamente y, a continuación, desinstalado, debe asegurarse de que no hay servicios WFA en ese sistema.
* Debe haber descargado el instalador de WFA desde el sitio de soporte de NetApp.
* Debe deshabilitar el `Auto upgrade` Característica de Java.


.Acerca de esta tarea
* Si está instalando WFA en una máquina virtual (VM), el nombre de la máquina virtual no debe incluir el carácter de guion bajo (_).
* ActiveState ActivePerl se instala antes de instalar WFA.
+
Esta instalación no afecta a ninguna otra instancia de ActivePerl que haya instalado en su servidor WFA.

* Antes de reinstalar WFA 4.2 o posterior, debe eliminar el directorio de datos MySQL si ha desinstalado MySQL.
* Si instala MySQL por su cuenta, WFA establece el `secure-file-privilege` y la `sql-mode` Propiedades en MySQL `my.ini` archivo en blanco.


.Pasos
. Inicie sesión en Windows con una cuenta con permisos administrativos.
. Abra el Explorador de Windows y, a continuación, desplácese hasta el directorio donde se encuentra el archivo de instalación.
. Instalar WFA:
+
** Instalación interactiva
+
... Haga clic con el botón derecho del ratón y ejecute el ejecutable del instalador de WFA (`.exe`) como usuario administrador.
... Haga clic en *Siguiente*.
... Introduzca las credenciales del usuario administrador predeterminado y, a continuación, haga clic en *Siguiente*.
+
La contraseña de administrador predeterminada debe cumplir con los siguientes criterios:

+
**** Mínimo de seis caracteres
**** Un carácter en mayúscula
**** Un carácter en minúscula
**** Un número
**** Un carácter especial *Nota:* debe anotar las credenciales del usuario admin.


... Seleccione los puertos para la configuración de WFA y, a continuación, haga clic en *Siguiente*.
... Introduzca un nombre de sitio y el nombre de su empresa y, a continuación, haga clic en *Siguiente*.
+
El nombre del sitio puede incluir la ubicación de la instalación de WFA, por ejemplo, Pittsburgh, PA.

... Si desea cambiar la ubicación de instalación predeterminada, seleccione la ubicación en la que desea instalar WFA y, a continuación, haga clic en *Siguiente*.
... Si no desea cambiar la ubicación predeterminada de la base de datos de WFA, haga clic en *Siguiente*.
... Haga clic en *instalar* para continuar con la instalación.
... Haga clic en *Finalizar* para completar la instalación.
... Compruebe que WFA se haya instalado correctamente eligiendo una de las siguientes acciones:
+
**** Acceda a WFA mediante un navegador web.
**** Utilice la consola de servicios de Windows para comprobar que el servicio WFA Server de NetApp y el servicio WFA Database de NetApp están en ejecución.




** Instalación silenciosa (desde el símbolo del sistema): +
`WFA-version_number-build_number.exe /s /v"WFA_ADMIN_USERNAME=wfa_username WFA_ADMIN_PASSWORD=password WFA_ADMIN_CONFIRM_PASSWORD=confirm admin password / WFA_MYSQL_PASS=password CONFIRM_WFA_MYSQL_PASS=confirm MySQL password WFA_INSTALL_SITE=site WFA_INSTALL_ORGANIZATION=organization_name WFA_HTTP_PORT=port WFA_HTTPS_PORT=port INSTALLDIR=install_directory DATABASEDIR=database_directory /qr /l*v C:\install.log"`
+
*ejemplo*

+
`WFA-x64-v4.2.0.0.0-B2973881.exe /s /v"WFA_ADMIN_USERNAME=admin WFA_ADMIN_PASSWORD=Company*234 WFA_ADMIN_CONFIRM_PASSWORD=Company*234 WFA_MYSQL_PASS=MySQL*234 CONFIRM_WFA_MYSQL_PASS=MySQL*234 WFA_INSTALL_SITE=nb WFA_INSTALL_ORGANIZATION=netapp WFA_HTTP_PORT=9090 WFA_HTTPS_PORT=8443 INSTALLDIR=\"C:\Program Files\NetApp\WFA\" DATABASEDIR=\"C:\Program Files\NetApp\WFA\Database\" /qr /l*v C:\install.log"`

+

NOTE: La `/qn` La opción no es compatible con WFA.

+
Los parámetros del comando son los siguientes:

+
[cols="2*"]
|===
| Parámetro | Descripción 


 a| 
_WFA_ADMIN_USERNAME_
 a| 
Nombre de usuario del administrador

Parámetro opcional. Si no se especifica un valor, se utiliza el valor predeterminado admin.



 a| 
_WFA_ADMIN_PASSWORD_
 a| 
Contraseña de usuario administrador

Parámetro obligatorio. La contraseña de administrador predeterminada debe cumplir con los siguientes criterios:

*** Mínimo de seis caracteres
*** Un carácter en mayúscula
*** Un carácter en minúscula
*** Un número
*** Un carácter especial




 a| 
_WFA_ADMIN_CONFIRM_PASSWORD_
 a| 
Contraseña de usuario administrador

Parámetro obligatorio



 a| 
_WFA_MYSQL_PASS_
 a| 
Contraseña de usuario MySQL

Parámetro obligatorio



 a| 
_CONFIRM_WFA_MYSQL_PASS_
 a| 
Contraseña de usuario MySQL

Parámetro obligatorio



 a| 
_WFA_INSTALL_SITE_
 a| 
Unidad organizativa en la que se instala WFA parámetro obligatorio



 a| 
_WFA_INSTALL_ORGANIZATION_
 a| 
Nombre de la organización o empresa donde se está instalando WFA

Parámetro obligatorio



 a| 
_WFA_HTTP_PORT_
 a| 
Parámetro opcional del puerto HTTP. Si no se especifica un valor, se utiliza el valor predeterminado 80.



 a| 
_WFA_HTTPS_PORT_
 a| 
Parámetro opcional del puerto HTTPS. Si no se especifica un valor, se utiliza el valor predeterminado 443.



 a| 
_INSTALLDIR_
 a| 
Ruta del directorio de instalación

Parámetro opcional. Si no especifica un valor, entonces la ruta predeterminada `"C:\Program Files\NetApp\WFA\"` se utiliza.

|===




*Información relacionada*

http://mysupport.netapp.com["Soporte de NetApp"]
