---
permalink: windows-install/task-upgrade-active-state-perl-on-windows.html 
sidebar: sidebar 
keywords: oncommand workflow automation, upgrade, activestate, perl 
summary: 'OnCommand Workflow Automation (WFA) funciona con la edición empresarial de ActiveState Perl en Windows. Puede actualizar a una versión más reciente de ActiveState Perl para obtener soluciones para vulnerabilidades de seguridad en el servidor Windows.' 
---
= Actualice ActiveState Perl
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) funciona con la edición empresarial de ActiveState Perl en Windows. Puede actualizar a una versión más reciente de ActiveState Perl para obtener soluciones para vulnerabilidades de seguridad en el servidor Windows.

.Lo que necesitará
Debe tener privilegios de administrador de Windows en el servidor de WFA. ActiveState Perl no admite actualizaciones «in situ».

.Acerca de esta tarea
WFA 5.0 usa la edición Enterprise de ActiveState Perl.

Puede actualizar desde ActiveState Perl 5.16.3 compilación 1603.14 a versiones posteriores. No puede actualizar a una versión principal de ActiveState Perl.

.Pasos
. Inicie sesión como usuario administrador en el equipo host de WFA.
. Descargue la última versión de ActiveState Enterprise Edition 5.16.3 de 64 bits en el sistema de destino.
. Utilice la consola de servicios de Windows para detener los siguientes servicios de WFA:
+
** WFA Database o MYSQL57
** Servidor WFA


. Desinstale la versión actual de ActiveState Perl en el sistema de destino desde el panel de control.
. Realice una copia de seguridad del `C:\Perl64\site\lib` carpeta.
. Instale el nuevo ActiveState Enterprise Edition en el equipo de destino.
. Restaure el `\site\lib` Carpeta de ActiveState Enterprise Edition cuya copia de seguridad creó en el paso 5.
. Reinicie los servicios de WFA mediante la consola de servicios de Windows.

