---
permalink: windows-install/task-modify-the-default-password-policy-windows.html 
sidebar: sidebar 
keywords: modify, default, password, policy, windows 
summary: 'OnCommand Workflow Automation (WFA) aplica una política de contraseñas para los usuarios locales. Puede modificar la directiva de contraseñas predeterminada para establecer una contraseña según sus necesidades.' 
---
= Modifique la directiva de contraseñas predeterminada para Windows
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) aplica una política de contraseñas para los usuarios locales. Puede modificar la directiva de contraseñas predeterminada para establecer una contraseña según sus necesidades.

.Lo que necesitará
Debe haber iniciado sesión en el sistema host de WFA como usuario raíz.

.Acerca de esta tarea
* La ruta de instalación predeterminada de WFA se utiliza en este procedimiento.
+
Si ha cambiado la ubicación predeterminada durante la instalación, debe utilizar la ruta de instalación personalizada de WFA.

* El comando para modificar la política de contraseñas predeterminada es `.\wfa --password-policy=default.`
+
El valor predeterminado es "minLength=true,6;specialChar=true,1;digitalChar=true,1;lowercaChar=true,1;uppercaseChar=true,1;espaceChar=false".

+
De acuerdo con esta configuración de la política de contraseñas predeterminada, la contraseña debe tener una longitud mínima de seis caracteres, debe contener al menos un carácter especial, un dígito, un carácter en minúscula y un carácter en mayúscula, y no debe contener espacios.



.Pasos
. En el símbolo del sistema, desplácese hasta el siguiente directorio en el servidor WFA:
+
`WFA_install_location/wfa/bin/`

. Modifique la política de contraseñas predeterminada:
+
`.\wfa --password-policy=PasswordPolicyString --restart=WFA`


