---
permalink: windows-install/task-replace-the-default-workflow-automation-ssl-certificate.html 
sidebar: sidebar 
keywords: replace, default, workflow, automation, ssl, certificate 
summary: 'Puede reemplazar el certificado SSL predeterminado de Workflow Automation (WFA) si el certificado ha caducado o si desea aumentar el período de validez del certificado.' 
---
= Reemplace el certificado SSL predeterminado de Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede reemplazar el certificado SSL predeterminado de Workflow Automation (WFA) si el certificado ha caducado o si desea aumentar el período de validez del certificado.

.Lo que necesitará
Debe tener privilegios de administrador de Windows en el servidor de WFA.

.Acerca de esta tarea
La ruta de instalación predeterminada de WFA se utiliza en este procedimiento. Si ha cambiado la ubicación predeterminada durante la instalación, debe utilizar la ruta de instalación personalizada de WFA.

.Pasos
. Inicie sesión como usuario administrador en el equipo host de WFA.
. Utilice la consola de servicios de Windows para detener los siguientes servicios de WFA:
+
** Base de datos WFA de NetApp
** Servidor WFA de NetApp


. Elimine el `wfa.keystore` archivo desde la siguiente ubicación: `<WFA_install_location>\WFA\jboss\standalone\configuration\keystore`
. Abra un símbolo del sistema en el servidor de WFA y cambie los directorios a la siguiente ubicación:
+
`<WFA_install_location>\WFA\jre\bin`

. Obtenga la clave de la base de datos: `keytool -keysize 2048 -genkey -alias "ssl keystore" -keyalg RSA -keystore "<WFA_install_location>\WFA\jboss\standalone\configuration\keystore\wfa.keystore" -validity xxxx`
+
`xxxx` es el número de días para la validez del certificado nuevo.

. Cuando se le solicite, introduzca la contraseña (predeterminada o nueva).
+
`changeit` es la contraseña predeterminada. Si no desea utilizar la contraseña predeterminada, debe cambiar el atributo de contraseña del elemento SSL del `standalone-full.xml` archivo desde la siguiente ubicación: `<WFA_install_location>\WFA\jboss\standalone\configuration\`

+
*ejemplo*

+
[listing]
----
<ssl name="ssl" password="new_password" certificate-key-file="${jboss.server.config.dir}/keystore/wfa.keystore"
----
. Introduzca los detalles obligatorios para el certificado.
. Revise la información que se muestra y escriba `Yes`.
. Pulse *Intro* cuando se le solicite el siguiente mensaje: `Enter key password for <SSL keystore> <RETURN if same as keystore password>.`
. Reinicie los servicios de WFA mediante la consola de servicios de Windows.

