---
permalink: windows-install/task-manage-site-specific-perl-modules.html 
sidebar: sidebar 
keywords: manage, site-specific, perl modules 
summary: 'Puede utilizar ActiveState Perl Package Manager (PPM) para gestionar los módulos Perl específicos de su sitio. Debe instalar módulos Perl específicos de su sitio fuera del directorio de instalación de OnCommand Workflow Automation (WFA) para evitar la eliminación de sus módulos Perl durante una actualización a WFA.' 
---
= Gestione módulos Perl específicos para cada sitio
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Puede utilizar ActiveState Perl Package Manager (PPM) para gestionar los módulos Perl específicos de su sitio. Debe instalar módulos Perl específicos de su sitio fuera del directorio de instalación de OnCommand Workflow Automation (WFA) para evitar la eliminación de sus módulos Perl durante una actualización a WFA.

.Acerca de esta tarea
Con la variable de entorno PERL5LIB, puede configurar el intérprete Perl instalado en el servidor WFA para utilizar sus módulos Perl.

La instalación del diminuto módulo Perl en el área de usuario de c:\Perl se utiliza como ejemplo en este procedimiento. Este área de usuario no se elimina cuando desinstala WFA, y puede reutilizar el área después de reinstalar o actualizar WFA.

.Pasos
. Establezca la variable de entorno PERL5LIB en la ubicación en la que desea instalar los módulos Perl.
+
*ejemplo*

+
`c:\>echo %PERL5LIB%`

+
`c:\Perl`

. *Opcional:* Verifique que el área del módulo Perl no se inicializa utilizando `ppm area list`.
+
*ejemplo*

+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area list`

+
[listing]
----
┌────────┬──────┬───────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                               │
├────────┼──────┼───────────────────────────────────────────────────┤
│ (user) │  n/a │ C:/Perl                                           │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib       │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib            │
└────────┴──────┴───────────────────────────────────────────────────┘
----
. Inicialice el área del módulo Perl usando `ppm area init user`.
+
*ejemplo*

+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area init user`

+
[listing]
----
Syncing user PPM database with .packlists...done
----
. *Opcional:* Verifique que el área del módulo Perl se inicializa utilizando `ppm area list`.
+
*ejemplo*

+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area list`

+
[listing]
----
┌────────┬──────┬───────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                               │
├────────┼──────┼───────────────────────────────────────────────────┤
│  user  │  0   │ C:/Perl                                           │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib       │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib            │
└────────┴──────┴───────────────────────────────────────────────────┘
----
. Añada los repositorios necesarios e instale los paquetes necesarios.
+
.. Añada el repositorio requerido mediante `ppm repo add`.
+
*ejemplo*

+
`+c:\Program Files\NetApp\WFA\Perl64\bin>ppm repo add http://ppm4.activestate.com/MSWin32-x64/5.16/1600/package.xml+`

+
[listing]
----
Downloading ppm4.activestate.com packlist...done
Updating ppm4.activestate.com database...done
Repo 1 added.
----
.. *Opcional:* Verifique que el repositorio requerido se agregue mediante el uso `ppm repo list`.
+
*ejemplo*

+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm repo list`

+
[listing]
----
┌────────┬──────┬────────────────────────────────────────────────┐
│ id     │ pkgs │ name                                           │
├────────┼──────┼────────────────────────────────────────────────┤
│  1     │17180 │ ppmr.activestate.com                           │
└────────┴──────┴────────────────────────────────────────────────┘
 (1 enabled repository)
----
.. Instale el módulo Perl necesario usando `ppm install`.
+
*ejemplo*

+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm install Try-Tiny --area user`

+
[listing]
----
Downloading ppm4.activestate.com packlist...done
Updating ppm4.activestate.com database...done
Downloading Try-Tiny-0.18...done
Unpacking Try-Tiny-0.18...done
Generating HTML for Try-Tiny-0.18...done
Updating files in user area...done
   2 files installed
----
.. *Opcional:* Verifique que el módulo Perl necesario se instale utilizando `ppm area list`.
+
*ejemplo*

+
`c:\Program Files\NetApp\WFA\Perl64\bin>ppm area list`

+
[listing]
----
┌────────┬──────┬────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                            │
├────────┼──────┼────────────────────────────────────────────────┤
│  user  │  1   │ C:/Perl                                        │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib    │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib         │
└────────┴──────┴────────────────────────────────────────────────┘
----



