---
permalink: help/concept-advanced-configuring-oncommand-workflow-automation.html 
sidebar: sidebar 
keywords: configure, oncommand workflow automation, wfa, autosupport 
summary: 'OnCommand Workflow Automation (WFA) le permite configurar varios ajustes. Por ejemplo, AutoSupport y notificaciones.' 
---
= Configurando OnCommand Workflow Automation
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation (WFA) le permite configurar diversos ajustes, por ejemplo, AutoSupport y notificaciones.

Al configurar WFA, puede configurar una o varias de las siguientes opciones, según sea necesario:

* AutoSupport (ASUP) para enviar mensajes de ASUP al soporte técnico
* Servidor de Microsoft Active Directory Lightweight Directory Access Protocol (LDAP) para la autenticación y autorización de LDAP para usuarios de WFA
* Envíe un correo electrónico para notificaciones por correo electrónico sobre operaciones de flujo de trabajo y envío de mensajes de ASUP
* Protocolo simple de gestión de red (SNMP) para recibir notificaciones sobre operaciones de flujos de trabajo
* Syslog para registro remoto de datos

